name: Build & Deploy Pages
on:
  workflow_dispatch:        # запуск вручную
  schedule:
    - cron: "*/15 * * * *"  # каждые 15 минут
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python parser.py          # генерируем site
      - uses: actions/upload-pages-artifact@v3
        with: {path: .}                # отдаём всё содержимое
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
